### PR TITLE
creating a nav-bar -- task1 #404

### PR DESCRIPTION
**Pull request by Jony-Jas**
Created a Nav bar
Task 1 #404

### CODE REVIEW

**Comment by Jony-Jas** [comment]
What content should I add to --> Coding Contest Page and Hackathons Page?

* I think first we should separate the data into a JSON file.
* And add a category section in the data

or any other ways?

**Comment by avinash201199** [comment]
good work :)

**Comment by avinash201199** [comment]
> What content should I add to --> Coding Contest Page and Hackathons Page?
> 
> * I think first we should separate the data into a JSON file.
> * And add a category section in the data
> 
> or any other ways?

for coding contest page and hackathon page we have two diretory where contents are already present and people are adding more , so if people will add any competion or any program then they will add the details in main page readme as well is in script.js file . If the contributer will add details of any coding contest then he have to add details in coding contest folder's readme file and in coding.js file like wise for hackathon.

**Comment by avinash201199** [comment]
so now we have to create 2 html file and two js file ( coding.html , hackathon.html , coding.js , hacktahon.js) 

same way as we are doing in home page

**Pull request merged**
