### PR TITLE
Removed some repeated ones and added TopCoder One

### PR DESCRIPTION
**Pull request by yadunandanbhat**
Removed Microsoft Imagine Cup and JPMC Code for Good, which was repeated twice and added Top Coder Open, and rearranged the Code Gladiators

### CODE REVIEW

**Comment by avinash201199** [comment]
I didn't find those two repeated, can you add a screenshot?

**Comment by avinash201199** [comment]
Now, I can see Microsoft imagine cup is repeated but didn't find JPMC code repeated.

**Comment by yadunandanbhat** [comment]
Because in the first image its under the name "JPMorgan Code for good" and in the second image it's named just "code for good"

**Comment by avinash201199** [comment]
Thank you :) 
Good work @yadunandanbhat

**Pull request merged**
