### PR TITLE
Adding JGEC details

### PR DESCRIPTION
**Pull request by Kumar-Ankit56**
Success resolve the issue no #177

### CODE REVIEW

**Comment by avinash201199** [comment]
also add details in script.js file so that it can reflect on website also , check contributing.md file

**Comment by Kumar-Ankit56** [comment]
> also add details in script.js file so that it can reflect on website also , check contributing.md file

Sure let me do changes

**Comment by Kumar-Ankit56** [comment]
@avinash201199 buddy once clearly me, Do I need to add in script file only or somewhere else as well

**Comment by Kumar-Ankit56** [comment]
@avinash201199 changes done

**Pull request merged**
