### PR TITLE
fully responsive website

### PR DESCRIPTION
**Pull request by Abhishek-thakur1**
This is the minimal and cool looking fully responsive website. you can check here https://compandprog.netlify.app/

### CODE REVIEW

**Comment by avinash201199** [comment]
great work Abhishek

**Comment by avinash201199** [comment]
before accepting the pr , I want to ask you is the file structure is same to host it here ?

**Comment by avinash201199** [comment]
image

website looks like this , can you guide me on this ?

**Comment by Abhishek-thakur1** [comment]
clone the repo, go to the site directory and install packages by `npm install` after that run `npm install gh-pages` the go to `package.json` file the in `scripts` section add these two `"predeploy": "npm run build"` and `"deploy": "gh-pages -d build"` (you can match the scripts sections with below image) and then you are good to go just run `npm run deploy`
Screenshot (33)

**Comment by Abhishek-thakur1** [comment]
just clone the repo and go to site directory by `cd site` in ur terminal and install the packages by `npm install` and then run `npm run deploy`

**Comment by Abhishek-thakur1** [comment]
any suggestions for changes will be welcomed...

**Comment by avinash201199** [comment]
@Abhishek-thakur1 
can you extract the html ,css and js part , I don't know typescript and it will be hard for others to contribute  , please share the extracted  code as zip file - https://www.linkedin.com/in/avinash-singh-071b79175/

**Comment by Abhishek-thakur1** [comment]
yeah sure

**Pull request merged**
