### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by avishi-bafna**

### CODE REVIEW

**Comment by avinash201199** [comment]
please resolve conflicts

**Comment by avinash201199** [comment]
reply challenge is already present

**Comment by avinash201199** [comment]
you have done some mistake in editing

**Comment by avinash201199** [comment]
I reverted the change

**Comment by avinash201199** [comment]
you can work on any other issue , thank you for contributing

**Comment by avishi-bafna** [comment]
Okay

**Pull request merged**
